### ISSUE TITLE
Error in Brackets

### ISSUE THREAD

**Issue by Denisov21** [Liongold/brackets-pdfexport#38]
Hi, 
1. Open Brackets 
2. I see this error:

![immagine 1 03082015](https://cloud.githubusercontent.com/assets/2547815/9040773/8a233a52-3a04-11e5-827c-1f65bec7f916.png)

**Comment by Liongold** [comment]
@Denisov21 What were you trying to do? Also can you show me the console, please?

**Comment by Denisov21** [comment]
That is the console

![immagine 7 03082015](https://cloud.githubusercontent.com/assets/2547815/9043375/4efcad58-3a15-11e5-85ca-35077d49d29d.png)
![immagine 8 03082015](https://cloud.githubusercontent.com/assets/2547815/9043376/4f01f574-3a15-11e5-80e5-37091e1e28a8.png)
![immagine 9 03082015](https://cloud.githubusercontent.com/assets/2547815/9043377/4f095c60-3a15-11e5-8ff0-2b5a41b89e72.png)
![immagine 10 03082015](https://cloud.githubusercontent.com/assets/2547815/9043380/4f17b45e-3a15-11e5-92d9-a465c0f95907.png)
![immagine 11 03082015](https://cloud.githubusercontent.com/assets/2547815/9043378/4f12688c-3a15-11e5-858e-80c988f75908.png)
![immagine 12 03082015](https://cloud.githubusercontent.com/assets/2547815/9043379/4f17d68c-3a15-11e5-8a25-27aeabcbd5bc.png)

Nothing, I did not understand anything about these warnings and errors in the console

**Comment by Liongold** [comment]
@Denisov21 Can you try disablign all extensions and enable only Export PDF, please?

**Comment by Denisov21** [comment]
The issue resolved @Liongold!

**Comment by Denisov21** [comment]
This extension causes error
https://github.com/DoersGuild/brackets-phplint

**Comment by Liongold** [comment]
@Denisov21 Good to know your issue is resolved. However, I'll try to force the error prompts to be triggered only when the extension gets an error (as it's supposed to be) so I won't close this for now. Thanks for the feedback.

**Comment by Liongold** [comment]
@Denisov21 I'll proceed in closing this issue since I've released 1.0.1 that includes a fix for this problem together with the updated translation. Thanks for your help. If you encounter any new issues, please file a new issue.
