### ISSUE TITLE
Wish: select Export Current file at the startup

### ISSUE THREAD

**Issue by Denisov21** [Liongold/brackets-pdfexport#39]
Hi @Liongold 
I wish select "Export Current file at he startup.
Now:

![immagine 1 05082015](https://cloud.githubusercontent.com/assets/2547815/9091048/3968ec2e-3b9e-11e5-8b12-b3477e79b672.png)

Wish:

![immagine 2 05082015](https://cloud.githubusercontent.com/assets/2547815/9091086/80fa4510-3b9e-11e5-901b-6e512ae41521.png)

**Comment by Liongold** [comment]
@Denisov21 Can you set it using the Set Defaults form?

**Comment by Denisov21** [comment]
Yes, of course!
