### ISSUE TITLE
Undefine with Export as PDF

### ISSUE THREAD

**Issue by nhhoangctu** [Liongold/brackets-pdfexport#42]
Hi,
I have a problem when I "Export as PDF" with "Export Selection" mode.
Pleasae help me!
![issue](https://cloud.githubusercontent.com/assets/9614754/9339818/573e496a-4616-11e5-986d-7887ba938c5a.png)

**Comment by Liongold** [comment]
@nhhoangctu Thanks for submitting this report. Does this happen with every document you export or just with a particular one?

**Comment by nhhoangctu** [comment]
@Liongold 
Hi Liongold,

This happen with every document
First, I select some code. 
Then, I go View>Export as PDF.
Next, select "Export Selection" mode. 

It has problem with Export Selection mode.
Export Current File hasn't problem!

**Comment by nhhoangctu** [comment]
Please help me fix it. I don't know to fix this problem.

Thanks a lot

**Comment by Liongold** [comment]
@nhhoangctu Sorry for prematurely closing the issue. It was done by Github automatically. The issue has now been fixed. I've uploaded a new release to Github and the Extension Registry where the fix is included. Please test version 1.0.2 and report back if you encounter any problems. Thanks for your interest and contribution to the extension.

**Comment by nhhoangctu** [comment]
Okie, this problem fixed! I just updated new vesion!

Thanks a lot Liongold
 NguyenHuyHoang 


     Vào ngày 22:26 Thứ Sáu, 21 tháng 8 2015, Liongold <notifications@github.com> đã viết:
   

 @nhhoangctu Sorry for prematurely closing the issue. It was done by Github automatically. The issue has now been fixed. I've uploaded a new release to Github and the Extension Registry where the fix is included. Please test version 1.0.2 and report back if you encounter any problems. Thanks for your interest and contribution to the extension. —

**Comment by Liongold** [comment]
Glad it's fixed.
