### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jlaurrieta** [Liongold/brackets-pdfexport#47]
when trying to convert a project to PDF it simply darkens Brackets window and doesn´t generate the file

**Comment by Liongold** [comment]
Can you give some more details about your issue please? Here are some key things you should mention. 

- Brackets version
- Type of export (selection or whole file)
- Any console output (Debug > Show Developer Tools)
- Does the issue occur again if you disable all extensions except this one?
- How large is the text you're trying to export?

**Comment by Liongold** [comment]
Since this issue could not be reconfirmed, has not had a reply for a long time and new versions of the extension have been released since the last comment, this issue will be closed. Thanks for your interest in Export PDF.
