### ISSUE TITLE
Export is not happening

### ISSUE THREAD

**Issue by manojbabu** [Liongold/brackets-pdfexport#48]
![2016-05-02_194257](https://cloud.githubusercontent.com/assets/5120866/14956568/17d6567a-109e-11e6-9be5-df07cf047fa3.png)

**Comment by Liongold** [comment]
@manojbabu Can you open the Brackets console and show its output (especially errors)? Please also include which setting you were using (selection or whole file) and your Brackets version. Please also try to reproduce this issue after reloading Brackets with all extensions disabled (except this one of course). Thanks.

**Comment by Liongold** [comment]
Since this issue could not be reconfirmed, has not had a reply for a long time and new versions of the extension have been released since the last comment, this issue will be closed. Thanks for your interest in Export PDF.
