### ISSUE TITLE
User configurable margins on exported PDF document

### ISSUE THREAD

**Issue by Denisov21** [Liongold/brackets-pdfexport#9]
I read this https://github.com/adobe/brackets/issues/7580#issuecomment-53130792 this is my feedback
I would like if possible:

1 Open the pdf file created (if a checkbox is selected) 
2 Remove the margins

**Comment by Liongold** [comment]
I have done the UI fields required for this task in the Options dialog rewrite.

**Comment by Liongold** [comment]
Work on this is ongoing in branch issue-#9. Any comments should be posted there. Work on the feature is almost ready and once tested in a more full way will be merged.

**Comment by Liongold** [comment]
This has now been fixed. If you encounter any issues, please open a new bug report.
